### PR TITLE
Ruben Cedeno - Functions Deliverable

### PR DESCRIPTION
**Pull request by anonyymous1**
**Deliverable Submission**

Please describe your comfort and completeness levels before submitting.

Comfort Level (1-5): 3.5

Completeness Level (1-5):4

Do you have any remaining questions about this deliverable?: Many

### CODE REVIEW

**Comment by mkzarra** [comment]
I'd love to hear your questions! This was a hard one. good work.

**Comment by anonyymous1** [comment]
Hey Mike,

I didn’t receive a email for my Airbnb homework, is that just because it’s still being processed or did I submit it wrong?

**Comment by mkzarra** [comment]
Dexter closed and commented that PR. You did well

**Comment by anonyymous1** [comment]
Got it, sorry about that I didn’t see this before contacting you on slack. My apologies. Have a great weekend.

**Pull request closed without merging**
